version: 2

sources:
  - name: api_sources
    database: CAPSTONE_FINAL
    schema: RAW
    tables:
      - name: live_rates
        description: "Exchange rate data ingested from exchangerate.host API"
        columns:
          - name: BASE
            description: "Base currency"
          - name: DATE
            description: "Unix timestamp"
          - name: RATES
            description: "JSON object of currency rates"
          - name: FULL_RESPONSE
            description: "Full API response as JSON"
          - name: INGESTED_AT
            description: "Timestamp when data was ingested"

      - name: currency
        description: "Currency data with codes and names"
        columns:
          - name: CURRENCY
            description: "Name of the currency"
          - name: CODE
            description: "ISO code of the currency"