version: 2

sources:
  - name: api_sources
    database: CAPSTONE_FINAL
    schema: RAW
    tables:
      - name: live_rates
        description: "Exchange rate data ingested from exchangerate.host API"
        columns:
          - name: BASE
            description: "Base currency"
          - name: DATE
            description: "Unix timestamp"
          - name: RATES
            description: "JSON object of currency rates"
          - name: FULL_RESPONSE
            description: "Full API response as JSON"
          - name: INGESTED_AT
            description: "Timestamp when data was ingested"