version: 2

sources:
  - name: sc_lab_m1w4
    database: CAPSTONE
    schema: SC_LAB_M1W4
    tables:
      - name: forex_crypto_rates_wayne
        description: "Raw forex and crypto exchange rates"
        columns:
          - name: base_currency
            description: "The base currency code"
          - name: quote_currency
            description: "The quote currency code"
          - name: exchange_rate
            description: "The exchange rate value"
          - name: timestamp
            description: "The timestamp of the rate"

  - name: exchange_rates_bronze
    database: CAPSTONE
    schema: EXCHANGE_RATES_BRONZE
    tables:
      - name: RAW_KAFKA_EVENTS
        description: "Raw events ingested from Kafka via Snowflake connector"
        columns:
          - name: RECORD_METADATA
            description: "Kafka metadata"
          - name: RECORD_CONTENT
            description: "Event payload"
      - name: RAW_KAFKA_EVENTS_FLAT
        description: "Flattened Kafka events with separate columns"
        columns:
          - name: BASE_CURRENCY
            description: "The base currency code"
          - name: QUOTE_CURRENCY
            description: "The quote currency code"
          - name: EXCHANGE_RATE
            description: "The exchange rate value"
          - name: TIMESTAMP
            description: "The timestamp of the rate"