name: dbt CI/CD

on:
  pull_request:
    branches: [ main, transform-task ]  

jobs:
  dbt-checks:
    runs-on: ubuntu-latest
    env:
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
      SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
      SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
      SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
      SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
      SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dbt and sqlfluff
        run: |
          pip install dbt-snowflake sqlfluff

      - name: Install dbt packages
        run: dbt deps
        working-directory: dbt_dag/dags/dbt/dbt_capstone_project

      - name: Run dbt tests
        run: dbt test
        working-directory: dbt_dag/dags/dbt/dbt_capstone_project

      - name: Run SQLFluff lint
        run: sqlfluff lint models/ --dialect snowflake
        working-directory: dbt_dag/dags/dbt/dbt_capstone_project